import { Procedure, ProcedureCategory } from "@/src/types/procedure";
import { ColumnDefinition } from "./patient";
import { i18n } from "@/src/lib/i18n";

export const PROCEDURE_COLUMNS: ColumnDefinition<Procedure>[] = [
  {
    name: "name",
    label: i18n.t("models.procedure.name"),
    type: "text",
    width: "100",
    required: true,
    placeholder: i18n.t("models.procedure.name"),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "code",
    label: i18n.t("models.procedure.code"),
    type: "text",
    width: "25",
    placeholder: i18n.t("models.procedure.code"),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "category",
    label: i18n.t("models.procedure.category"),
    type: "select",
    width: "25",
    required: true,
    options: Object.values(ProcedureCategory).map((s) => ({
      label: i18n.t(`enums.procedure_category.${s.toLowerCase()}`),
      value: s,
    })),
    grid: true,
    form: true,
    details: true,
    badge: true,
  },
  {
    name: "dispatch_role_ids",
    label: i18n.t("models.procedure.dispatch_roles"),
    type: "multi_search_input",
    width: "50",
    grid: false,
    form: true,
    details: false,
  },
  {
    name: "execute_role_ids",
    label: i18n.t("models.procedure.execute_roles"),
    type: "multi_search_input",
    width: "50",
    grid: false,
    form: true,
    details: false,
  },
  {
    name: "dispatch_roles",
    label: i18n.t("models.procedure.dispatch_roles"),
    type: "text",
    grid: true,
    form: false,
    details: true,
    render: (item: Procedure) => item.dispatch_roles?.map(r => r.name).join(", ") || "—",
  },
  {
    name: "execute_roles",
    label: i18n.t("models.procedure.execute_roles"),
    type: "text",
    grid: true,
    form: false,
    details: true,
    render: (item: Procedure) => item.execute_roles?.map(r => r.name).join(", ") || "—",
  },
  {
    name: "description",
    label: i18n.t("models.procedure.description"),
    type: "textarea",
    width: "100",
    placeholder: i18n.t("models.procedure.description"),
    grid: false,
    form: true,
    details: true,
  },
];
