"""updating_procedure_and_adding_attendance_procedure

Revision ID: 49cc4663ea29
Revises: 2d86b8d15a58
Create Date: 2026-05-25 19:50:23.986976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cc4663ea29'
down_revision = '2d86b8d15a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_procedures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_id', sa.BigInteger(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('ordered_by_id', sa.BigInteger(), nullable=True),
    sa.Column('executed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['executed_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_procedures_id'), 'attendance_procedures', ['id'], unique=False)
    op.create_table('attendance_procedure_medications',
    sa.Column('attendance_procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_procedure_id'], ['attendance_procedures.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('attendance_procedure_id', 'medication_id')
    )
    op.add_column('procedures', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('procedures', sa.Column('category', sa.Enum('screening', 'exam', 'surgery', 'consultation', 'nursing', 'therapy', 'other', name='procedurecategory', native_enum=False), server_default='other', nullable=False))
    op.create_index(op.f('ix_procedures_code'), 'procedures', ['code'], unique=False)
    op.drop_column('procedures', 'tuss_code')
    op.drop_column('procedures', 'sector')
    op.drop_column('procedures', 'cid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('cid', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('tuss_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_procedures_code'), table_name='procedures')
    op.drop_column('procedures', 'category')
    op.drop_column('procedures', 'code')
    op.drop_table('attendance_procedure_medications')
    op.drop_index(op.f('ix_attendance_procedures_id'), table_name='attendance_procedures')
    op.drop_table('attendance_procedures')
    # ### end Alembic commands ###
