"""split procedure roles dispatch execute

Revision ID: 6a006d56d644
Revises: 5e3cc9736be6
Create Date: 2026-05-26 15:27:40.289874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a006d56d644'
down_revision = '5e3cc9736be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_dispatch_roles',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'role_id')
    )
    op.create_table('procedure_execute_roles',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'role_id')
    )
    op.drop_table('procedure_responsible_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_responsible_roles',
    sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name=op.f('procedure_responsible_roles_procedure_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('procedure_responsible_roles_role_id_fkey')),
    sa.PrimaryKeyConstraint('procedure_id', 'role_id', name=op.f('procedure_responsible_roles_pkey'))
    )
    op.drop_table('procedure_execute_roles')
    op.drop_table('procedure_dispatch_roles')
    # ### end Alembic commands ###
